# Generated by Django 5.2.4 on 2025-08-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smart_ratelimit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ratelimitcounter',
            new_name='django_smar_key_a333b4_idx',
            old_name='django_smar_key_24c4a0_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitcounter',
            new_name='django_smar_window__892d5c_idx',
            old_name='django_smar_window__3e0e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitentry',
            new_name='django_smar_key_af838f_idx',
            old_name='django_smar_key_8ff7e9_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitentry',
            new_name='django_smar_expires_684344_idx',
            old_name='django_smar_expires_f8e4cc_idx',
        ),
        migrations.RenameIndex(
            model_name='ratelimitentry',
            new_name='django_smar_key_59d90e_idx',
            old_name='django_smar_key_b42c8a_idx',
        ),
        migrations.AlterField(
            model_name='ratelimitconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ratelimitcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ratelimitentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
