"""Create the RateLimitRule model for dynamic, DB-backed rate limit rules."""

# Generated by Django 5.2.4 on 2026-06-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the RateLimitRule model."""

    dependencies = [
        ("django_smart_ratelimit", "0003_alter_ratelimitcounter_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "path_pattern",
                    models.CharField(
                        help_text="URL pattern (regex) this rule applies to, e.g. '^/api/'.",
                        max_length=255,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        default="ALL",
                        help_text="HTTP methods (comma-separated, e.g. 'GET,POST') or 'ALL'.",
                        max_length=50,
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        help_text="Rate limit string, e.g. '100/m', '1000/h', '10/30s'.",
                        max_length=50,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        default="ip",
                        help_text="Key function (ip, user, header:X-API-Key, ...).",
                        max_length=100,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("fixed_window", "Fixed Window"),
                            ("sliding_window", "Sliding Window"),
                            ("token_bucket", "Token Bucket"),
                            ("leaky_bucket", "Leaky Bucket"),
                        ],
                        default="fixed_window",
                        max_length=50,
                    ),
                ),
                (
                    "block",
                    models.BooleanField(
                        default=True,
                        help_text="Block requests when the limit is exceeded.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Higher-priority rules are evaluated first.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "rate limit rule",
                "verbose_name_plural": "rate limit rules",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-priority"], name="ratelimit_rule_active"
                    )
                ],
            },
        ),
    ]
