"""Add the RateLimitEvent model for analytics/event logging."""

# Generated by Django 5.2.4 on 2026-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the RateLimitEvent model."""

    dependencies = [
        (
            "django_smart_ratelimit",
            "0005_usertier_userratelimitoverride_groupratelimit_apikey_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("rule_name", models.CharField(blank=True, max_length=100)),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("allowed", models.BooleanField()),
                ("count", models.PositiveBigIntegerField()),
                ("limit", models.PositiveBigIntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_id", models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["timestamp"], name="ratelimit_event_ts"),
                    models.Index(
                        fields=["key", "timestamp"], name="ratelimit_event_key_ts"
                    ),
                    models.Index(
                        fields=["allowed", "timestamp"],
                        name="ratelimit_event_allowed_ts",
                    ),
                ],
            },
        ),
    ]
