"""Add the TenantQuota model for per-tenant rate quotas."""

# Generated by Django 5.2.4 on 2026-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the TenantQuota model."""

    dependencies = [
        ("django_smart_ratelimit", "0006_ratelimitevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "rate",
                    models.CharField(
                        help_text="Rate string, e.g. '1000/h'.", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["tenant_id"],
            },
        ),
    ]
