"""Add the Quota model for cumulative long-horizon usage quotas."""

# Generated by Django 5.2.4 on 2026-06-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the Quota model."""

    dependencies = [
        ("django_smart_ratelimit", "0007_tenantquota"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                (
                    "scope",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Namespaces quotas.",
                        max_length=100,
                    ),
                ),
                ("used", models.PositiveBigIntegerField(default=0)),
                ("limit", models.PositiveBigIntegerField()),
                (
                    "period",
                    models.CharField(
                        help_text="day | week | month | year | <N>d", max_length=20
                    ),
                ),
                ("period_start", models.DateTimeField()),
                ("reset_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["key", "scope"], name="django_smar_key_20606f_idx"
                    ),
                    models.Index(
                        fields=["reset_at"], name="django_smar_reset_a_42fbf4_idx"
                    ),
                ],
                "unique_together": {("key", "scope")},
            },
        ),
    ]
